-- Create admin user for TCP connections
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'admin'@'127.0.0.1' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;
