# SQL database configuration
sql_driver = mysql

mysql 127.0.0.1 {
  user = dovecot
  password = DovecotPass2025!
  dbname = varmi_db
}

passdb sql {
  default_password_scheme = SHA512-CRYPT
  query = SELECT password FROM virtual_users WHERE email='%{user}'
}

userdb sql {
  query = SELECT 5000 AS uid, 5000 AS gid, '/var/mail/vhosts/%{user | domain}/%{user | username}' AS home, 'maildir:/var/mail/vhosts/%{user | domain}/%{user | username}' AS mail FROM virtual_users WHERE email='%{user}'
}
