
passdb sql {
  connect = host=127.0.0.1 dbname=varmi_db user=root password=Brkaydn426859..
  default_pass_scheme = SHA512-CRYPT
  password_query = SELECT email as user, password FROM virtual_users WHERE email='%u'
}

userdb static {
  args = uid=5000 gid=5000 home=/var/mail/vhosts/%d/%n
}
