# OpenDKIM Configuration
UserID                  opendkim
UMask                   007
Domain                  varmii.com
KeyFile                 /etc/opendkim/keys/varmii.com/mail.private
Selector                mail
Socket                  inet:8891@localhost
Canonicalization        relaxed/simple
Mode                    sv
SubDomains              no
AutoRestart             yes
AutoRestartRate         10/1M
Background              yes
DNSTimeout              5
SignatureAlgorithm      rsa-sha256
