server {
    listen 8081;
    server_name webmail.varmii.com;
    
    root /var/www/roundcube;
    index index.php index.html;
    
    access_log /var/log/nginx/roundcube-access.log;
    error_log /var/log/nginx/roundcube-error.log;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    
    location ~ /\.(ht|git|svn) {
        deny all;
    }
    
    location ^~ /temp/ {
        deny all;
    }
    
    location ^~ /logs/ {
        deny all;
    }
}
